void reset_to_98(int *);
void swap_int(int *, int *);
int _strlen(char *);
void _puts(char *);
int _putchar(char);
void print_rev(char *);
void rev_string(char *);
void puts2(char *);
void puts_half(char *);
char *_strcpy(char *, char *);
void print_array(int *, int);
int _atoi(char *);
void rev_string(char *);
char *_strcat(char *, char *);
char *_strncat(char *, char *, int);
char *_strncpy(char *, char *, int);
int _strcmp(char *, char *);
void reverse_array(int *, int);
char *string_toupper(char *);
char *cap_string(char *);
